FROM alpine:3.19
ENV TZ="Asia/Shanghai"
COPY ./smartdns /usr/sbin/
EXPOSE 53/udp 53/tcp
VOLUME "/etc/smartdns/"
HEALTHCHECK --interval=5m CMD test `nslookup dns.pub 127.0.0.1 |grep answer |wc -l` -gt 0
CMD ["/usr/sbin/smartdns", "run", "-c", "/etc/smartdns/smartdns.conf"]
