# .github/workflows/nightly.yml
name: Nightly builds

on:
  workflow_dispatch:
    inputs: 
      features:
        type: string
        required: false
        default: dns-over-tls,dns-over-https,dns-over-quic,dns-over-h3,dnssec,service,nft,self-update
  
  schedule:
    - cron:  '30 5,17 * * *'
  push:
    branches:
      - ci*

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      features: ${{inputs.features}}